name: test-script


on:
  push:
    branches:
      - master

env:
  cache-version: 'cache-v1'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.6', '4.0' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'print("hello")'

  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        R: [ '3.6', '4.0' ]
    name: windows-R-${{ matrix.R }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-R@master
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'print("hello")'

      - name: Install Windows system dependencies
        run: |
          ## Edit below if you have any Windows system dependencies
        shell: Rscript {0}

      - name: SessionInfo
        run: |
          sessionInfo()
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-R-${{ matrix.R }}-results
          path: check

  macOS:
    runs-on: macOS-latest

    strategy:
      matrix:
        R: [ '3.6', '4.0' ]
    name: macOS-R-${{ matrix.R }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-R@master
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'print("hello")'

      - name: Install macOS system dependencies
        run: |
          ## Enable installing XML from source if needed
          brew install libxml2
          echo "::set-env name=XML_CONFIG::/usr/local/opt/libxml2/bin/xml2-config"

          ## Required to install magick as noted at
          ## https://github.com/r-lib/usethis/commit/f1f1e0d10c1ebc75fd4c18fa7e2de4551fd9978f#diff-9bfee71065492f63457918efcd912cf2
          brew install imagemagick@6

      - name: SessionInfo
        run: |
          sessionInfo()
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-R-${{ matrix.R }}-results
          path: check