on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-script


env:
  cache-version: 'cache-v1'

jobs:
  
  linux-win-macOS-stable:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}-R-stable

    strategy:
      fail-fast: false
      matrix:
        config:
          ## Comment/Un-comment in case you also want to run other versions
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@master

      - name: Setup R from r-lib
        uses: r-lib/actions/setup-r@master

      - name: Install Linux system dependencies
        if: startsWith(runner.os, 'Linux')
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install libcurl4-openssl-dev libglpk-dev libmagick++-dev libnlopt-dev

      - name: Install macOS system dependencies
        if: startsWith(runner.os, 'macOS')
        run: |
          ## Enable installing XML from source if needed
          brew install libxml2
          echo "::set-env name=XML_CONFIG::/usr/local/opt/libxml2/bin/xml2-config"

          ## Required to install magick as noted at
          ## https://github.com/r-lib/usethis/commit/f1f1e0d10c1ebc75fd4c18fa7e2de4551fd9978f#diff-9bfee71065492f63457918efcd912cf2
          brew install imagemagick@6

      - name: Install Windows system dependencies
        if: startsWith(runner.os, 'Windows')
        run: |
          ## Edit below if you have any Windows system dependencies
        shell: Rscript {0}

      - name: Check cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/Library
          key: ${{ runner.os }}-renv-R-3-6-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-R-3-6-

      - name: Install requirements
        run: |
          source("Setup.R")
          sessionInfo()
        shell: Rscript {0}

      - name: Run SEMM_2020
        run: |
          library(rmarkdown)
          rmarkdown::render("Markdown_CE_Giulio.Rmd")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-biocbranch-${{ needs.define-docker-info.outputs.biocversion }}-r-${{ needs.R-CMD-check-bioc.outputs.rversion }}-bioc-${{ needs.define-docker-info.outputs.biocversion }}-results
          path: check

# with R.36

  linux-win-macOS-3_6:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}-R-3.6

    strategy:
      fail-fast: false
      matrix:
        config:
          ## Comment/Un-comment in case you also want to run other versions
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6

      - name: Install Linux system dependencies
        if: startsWith(runner.os, 'Linux')
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install libcurl4-openssl-dev libglpk-dev libmagick++-dev libnlopt-dev

      - name: Install macOS system dependencies
        if: startsWith(runner.os, 'macOS')
        run: |
          ## Enable installing XML from source if needed
          brew install libxml2
          echo "::set-env name=XML_CONFIG::/usr/local/opt/libxml2/bin/xml2-config"

          ## Required to install magick as noted at
          ## https://github.com/r-lib/usethis/commit/f1f1e0d10c1ebc75fd4c18fa7e2de4551fd9978f#diff-9bfee71065492f63457918efcd912cf2
          brew install imagemagick@6

      - name: Install Windows system dependencies
        if: startsWith(runner.os, 'Windows')
        run: |
          ## Edit below if you have any Windows system dependencies
        shell: Rscript {0}

      - name: Check cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/Library
          key: ${{ runner.os }}-renv-R-3-6-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-R-3-6-

      - name: Install requirements
        run: |
          source("Setup_36.R")
          sessionInfo()
        shell: Rscript {0}

      - name: Run SEMM_2020
        run: |
          library(rmarkdown)
          rmarkdown::render("Markdown_CE_Giulio.Rmd")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-biocbranch-${{ needs.define-docker-info.outputs.biocversion }}-r-${{ needs.R-CMD-check-bioc.outputs.rversion }}-bioc-${{ needs.define-docker-info.outputs.biocversion }}-results
          path: check
